vich_uploader:
    db_driver: orm
    metadata:
        type: attribute
    mappings:
       projects:
           uri_prefix: /images/projects
           upload_destination: '%kernel.project_dir%/public/images/projects'
